apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vaultwarden-admin
  namespace: vaultwarden
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: vaultwarden-admin
    creationPolicy: Owner
  data:
    - secretKey: admin-token
      remoteRef:
        key: VAULTWARDEN_ADMIN_TOKEN
