# SOPS configuration for secret encryption
# See: https://github.com/Mic92/sops-nix

keys:
  # node01 Age public key
  - &node01 age1qlysyzxnsejtaehxhpk20z0fumhtseamudqdpqvan037qfew6dusj7lurl

creation_rules:
  - path_regex: nix/hosts/node01/secrets\.yaml$
    key_groups:
      - age:
          - *node01

