# Doppler ClusterSecretStore
# Requires: Secret with Doppler Service Token in external-secrets namespace
#
# Create the token secret:
#   kubectl create secret generic doppler-token \
#     --namespace external-secrets \
#     --from-literal=token=dp.st.xxxx

apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: doppler
spec:
  provider:
    doppler:
      auth:
        secretRef:
          dopplerToken:
            name: doppler-token
            key: token
            namespace: external-secrets
