# Tailscale OAuth ExternalSecret
# Fetches client_id and client_secret from Doppler
# Requires: ClusterSecretStore 'doppler' to be ready
# Requires: Doppler secrets TAILSCALE_CLIENT_ID and TAILSCALE_CLIENT_SECRET

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tailscale-oauth
  namespace: tailscale
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: operator-oauth
    creationPolicy: Owner
  data:
    - secretKey: client_id
      remoteRef:
        key: TAILSCALE_CLIENT_ID
    - secretKey: client_secret
      remoteRef:
        key: TAILSCALE_CLIENT_SECRET
