apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-oidc
  namespace: nextcloud
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: nextcloud-oidc
    creationPolicy: Owner
  data:
    - secretKey: client-secret
      remoteRef:
        key: NEXTCLOUD_OIDC_CLIENT_SECRET
