apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-admin
  namespace: nextcloud
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: nextcloud-admin
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: NEXTCLOUD_ADMIN_USERNAME
    - secretKey: password
      remoteRef:
        key: NEXTCLOUD_ADMIN_PASSWORD
