apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-postgres-credentials
  namespace: immich
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: immich-postgres-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: password
      remoteRef:
        key: IMMICH_DB_PASSWORD
