apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - rbac.yaml
  - external-secret.yaml
  - cronjob.yaml

configMapGenerator:
  - name: ops-health-reporter-script
    namespace: ops-health-reporter
    files:
      - report.py

generatorOptions:
  disableNameSuffixHash: true
