apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ente-minio-data
  namespace: ente
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 50Gi
