apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ente-postgres-data
  namespace: ente
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
