apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ente-postgres-data
  namespace: ente
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
