apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: coder-postgres-credentials
  namespace: coder
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: coder-postgres-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: password
      remoteRef:
        key: CODER_DB_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: coder-db-url
  namespace: coder
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: coder-db-url
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: url
      remoteRef:
        key: CODER_DB_URL
