# K3s CoreDNS customization
# https://docs.k3s.io/networking/networking-services#coredns
# This ConfigMap adds a stub resolver for ts.net domain
# to forward queries to Tailscale's k8s-nameserver
# Uses fixed ClusterIP from ts-nameserver-fixed Service
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  tailscale.server: |
    ts.net {
      errors
      cache 30
      forward . 10.43.0.53
    }

