# Tailscale API Server Proxy RBAC
# Grant cluster-admin to Tailscale users
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tailscale-admin
subjects:
  - kind: User
    name: hikuohiku@gmail.com
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
